export enum CurrencyEnum {
  AFGHANISTAN = "AFN", // Afghan Afghani
  ALBANIA = "ALL", // Albanian Lek
  ALGERIA = "DZD", // Algerian Dinar
  ANDORRA = "EUR", // Euro
  ANGOLA = "AOA", // Angolan Kwanza
  ARGENTINA = "ARS", // Argentine Peso
  ARMENIA = "AMD", // Armenian Dram
  AUSTRALIA = "AUD", // Australian Dollar
  AUSTRIA = "EUR", // Euro
  AZERBAIJAN = "AZN", // Azerbaijani Manat
  BAHAMAS = "BSD", // Bahamian Dollar
  BAHRAIN = "BHD", // Bahraini Dinar
  BANGLADESH = "BDT", // Bangladeshi Taka
  BELGIUM = "EUR", // Euro
  BELIZE = "BZD", // Belize Dollar
  BENIN = "XOF", // West African CFA Franc
  BHUTAN = "BTN", // Bhutanese Ngultrum
  BOLIVIA = "BOB", // Bolivian Boliviano
  BOTSWANA = "BWP", // Botswana Pula
  BRAZIL = "BRL", // Brazilian Real
  BULGARIA = "BGN", // Bulgarian Lev
  BURKINA_FASO = "XOF", // West African CFA Franc
  CAMBODIA = "KHR", // Cambodian Riel
  CAMEROON = "XAF", // Central African CFA Franc
  CANADA = "CAD", // Canadian Dollar
  CHILE = "CLP", // Chilean Peso
  CHINA = "CNY", // Chinese Yuan
  COLOMBIA = "COP", // Colombian Peso
  COSTA_RICA = "CRC", // Costa Rican Colón
  CROATIA = "HRK", // Croatian Kuna
  CYPRUS = "EUR", // Euro
  CZECH_REPUBLIC = "CZK", // Czech Koruna
  DENMARK = "DKK", // Danish Krone
  ECUADOR = "USD", // US Dollar
  EGYPT = "EGP", // Egyptian Pound
  ESTONIA = "EUR", // Euro
  ETHIOPIA = "ETB", // Ethiopian Birr
  FINLAND = "EUR", // Euro
  FRANCE = "EUR", // Euro
  GERMANY = "EUR", // Euro
  GHANA = "GHS", // Ghanaian Cedi
  GREECE = "EUR", // Euro
  GUATEMALA = "GTQ", // Guatemalan Quetzal
  HUNGARY = "HUF", // Hungarian Forint
  ICELAND = "ISK", // Icelandic Króna
  INDIA = "INR", // Indian Rupee
  INDONESIA = "IDR", // Indonesian Rupiah
  IRAN = "IRR", // Iranian Rial
  IRAQ = "IQD", // Iraqi Dinar
  IRELAND = "EUR", // Euro
  ISRAEL = "ILS", // Israeli Shekel
  ITALY = "EUR", // Euro
  JAMAICA = "JMD", // Jamaican Dollar
  JAPAN = "JPY", // Japanese Yen
  JORDAN = "JOD", // Jordanian Dinar
  KAZAKHSTAN = "KZT", // Kazakhstani Tenge
  KENYA = "KES", // Kenyan Shilling
  KUWAIT = "KWD", // Kuwaiti Dinar
  LATVIA = "EUR", // Euro
  LEBANON = "LBP", // Lebanese Pound
  LIBYA = "LYD", // Libyan Dinar
  LITHUANIA = "EUR", // Euro
  LUXEMBOURG = "EUR", // Euro
  MALAYSIA = "MYR", // Malaysian Ringgit
  MALTA = "EUR", // Euro
  MEXICO = "MXN", // Mexican Peso
  MOLDOVA = "MDL", // Moldovan Leu
  MONACO = "EUR", // Euro
  MONGOLIA = "MNT", // Mongolian Tögrög
  MOROCCO = "MAD", // Moroccan Dirham
  NEPAL = "NPR", // Nepalese Rupee
  NETHERLANDS = "EUR", // Euro
  NEW_ZEALAND = "NZD", // New Zealand Dollar
  NIGERIA = "NGN", // Nigerian Naira
  NORTH_KOREA = "KPW", // North Korean Won
  NORWAY = "NOK", // Norwegian Krone
  OMAN = "OMR", // Omani Rial
  PAKISTAN = "PKR", // Pakistani Rupee
  PALESTINE = "ILS", // Israeli Shekel
  PANAMA = "PAB", // Panamanian Balboa
  PERU = "PEN", // Peruvian Sol
  PHILIPPINES = "PHP", // Philippine Peso
  POLAND = "PLN", // Polish Złoty
  PORTUGAL = "EUR", // Euro
  QATAR = "QAR", // Qatari Riyal
  ROMANIA = "RON", // Romanian Leu
  RUSSIA = "RUB", // Russian Ruble
  SAUDI_ARABIA = "SAR", // Saudi Riyal
  SENEGAL = "XOF", // West African CFA Franc
  SERBIA = "RSD", // Serbian Dinar
  SINGAPORE = "SGD", // Singapore Dollar
  SLOVAKIA = "EUR", // Euro
  SLOVENIA = "EUR", // Euro
  SOUTH_AFRICA = "ZAR", // South African Rand
  SOUTH_KOREA = "KRW", // South Korean Won
  SPAIN = "EUR", // Euro
  SRI_LANKA = "LKR", // Sri Lankan Rupee
  SUDAN = "SDG", // Sudanese Pound
  SWEDEN = "SEK", // Swedish Krona
  SWITZERLAND = "CHF", // Swiss Franc
  SYRIA = "SYP", // Syrian Pound
  TAIWAN = "TWD", // New Taiwan Dollar
  TANZANIA = "TZS", // Tanzanian Shilling
  THAILAND = "THB", // Thai Baht
  TUNISIA = "TND", // Tunisian Dinar
  TURKEY = "TRY", // Turkish Lira
  UKRAINE = "UAH", // Ukrainian Hryvnia
  UNITED_ARAB_EMIRATES = "AED", // UAE Dirham
  UNITED_KINGDOM = "GBP", // British Pound
  UNITED_STATES = "USD", // US Dollar
  URUGUAY = "UYU", // Uruguayan Peso
  UZBEKISTAN = "UZS", // Uzbekistani So'm
  VENEZUELA = "VES", // Venezuelan Bolívar
  VIETNAM = "VND", // Vietnamese Đồng
  YEMEN = "YER", // Yemeni Rial
  ZIMBABWE = "ZWL", // Zimbabwean Dollar
}

export enum CurrencyNameEnum {
  AFGHANISTAN = "Afghan Afghani",
  ALBANIA = "Albanian Lek",
  ALGERIA = "Algerian Dinar",
  ANDORRA = "Euro",
  ANGOLA = "Angolan Kwanza",
  ARGENTINA = "Argentine Peso",
  ARMENIA = "Armenian Dram",
  AUSTRALIA = "Australian Dollar",
  AUSTRIA = "Euro",
  AZERBAIJAN = "Azerbaijani Manat",
  BAHAMAS = "Bahamian Dollar",
  BAHRAIN = "Bahraini Dinar",
  BANGLADESH = "Bangladeshi Taka",
  BELGIUM = "Euro",
  BELIZE = "Belize Dollar",
  BENIN = "West African CFA Franc",
  BHUTAN = "Bhutanese Ngultrum",
  BOLIVIA = "Bolivian Boliviano",
  BOTSWANA = "Botswana Pula",
  BRAZIL = "Brazilian Real",
  BULGARIA = "Bulgarian Lev",
  BURKINA_FASO = "West African CFA Franc",
  CAMBODIA = "Cambodian Riel",
  CAMEROON = "Central African CFA Franc",
  CANADA = "Canadian Dollar",
  CHILE = "Chilean Peso",
  CHINA = "Chinese Yuan",
  COLOMBIA = "Colombian Peso",
  COSTA_RICA = "Costa Rican Colón",
  CROATIA = "Croatian Kuna",
  CYPRUS = "Euro",
  CZECH_REPUBLIC = "Czech Koruna",
  DENMARK = "Danish Krone",
  ECUADOR = "US Dollar",
  EGYPT = "Egyptian Pound",
  ESTONIA = "Euro",
  ETHIOPIA = "Ethiopian Birr",
  FINLAND = "Euro",
  FRANCE = "Euro",
  GERMANY = "Euro",
  GHANA = "Ghanaian Cedi",
  GREECE = "Euro",
  GUATEMALA = "Guatemalan Quetzal",
  HUNGARY = "Hungarian Forint",
  ICELAND = "Icelandic Króna",
  INDIA = "Indian Rupee",
  INDONESIA = "Indonesian Rupiah",
  IRAN = "Iranian Rial",
  IRAQ = "Iraqi Dinar",
  IRELAND = "Euro",
  ISRAEL = "Israeli Shekel",
  ITALY = "Euro",
  JAMAICA = "Jamaican Dollar",
  JAPAN = "Japanese Yen",
  JORDAN = "Jordanian Dinar",
  KAZAKHSTAN = "Kazakhstani Tenge",
  KENYA = "Kenyan Shilling",
  KUWAIT = "Kuwaiti Dinar",
  LATVIA = "Euro",
  LEBANON = "Lebanese Pound",
  LIBYA = "Libyan Dinar",
  LITHUANIA = "Euro",
  LUXEMBOURG = "Euro",
  MALAYSIA = "Malaysian Ringgit",
  MALTA = "Euro",
  MEXICO = "Mexican Peso",
  MOLDOVA = "Moldovan Leu",
  MONACO = "Euro",
  MONGOLIA = "Mongolian Tögrög",
  MOROCCO = "Moroccan Dirham",
  NEPAL = "Nepalese Rupee",
  NETHERLANDS = "Euro",
  NEW_ZEALAND = "New Zealand Dollar",
  NIGERIA = "Nigerian Naira",
  NORTH_KOREA = "North Korean Won",
  NORWAY = "Norwegian Krone",
  OMAN = "Omani Rial",
  PAKISTAN = "Pakistani Rupee",
  PALESTINE = "Israeli Shekel",
  PANAMA = "Panamanian Balboa",
  PERU = "Peruvian Sol",
  PHILIPPINES = "Philippine Peso",
  POLAND = "Polish Złoty",
  PORTUGAL = "Euro",
  QATAR = "Qatari Riyal",
  ROMANIA = "Romanian Leu",
  RUSSIA = "Russian Ruble",
  SAUDI_ARABIA = "Saudi Riyal",
  SENEGAL = "West African CFA Franc",
  SERBIA = "Serbian Dinar",
  SINGAPORE = "Singapore Dollar",
  SLOVAKIA = "Euro",
  SLOVENIA = "Euro",
  SOUTH_AFRICA = "South African Rand",
  SOUTH_KOREA = "South Korean Won",
  SPAIN = "Euro",
  SRI_LANKA = "Sri Lankan Rupee",
  SUDAN = "Sudanese Pound",
  SWEDEN = "Swedish Krona",
  SWITZERLAND = "Swiss Franc",
  SYRIA = "Syrian Pound",
  TAIWAN = "New Taiwan Dollar",
  TANZANIA = "Tanzanian Shilling",
  THAILAND = "Thai Baht",
  TUNISIA = "Tunisian Dinar",
  TURKEY = "Turkish Lira",
  UKRAINE = "Ukrainian Hryvnia",
  UNITED_ARAB_EMIRATES = "UAE Dirham",
  UNITED_KINGDOM = "British Pound",
  UNITED_STATES = "US Dollar",
  URUGUAY = "Uruguayan Peso",
  UZBEKISTAN = "Uzbekistani So'm",
  VENEZUELA = "Venezuelan Bolívar",
  VIETNAM = "Vietnamese Đồng",
  YEMEN = "Yemeni Rial",
  ZIMBABWE = "Zimbabwean Dollar",
}
